name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: prod.Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USER}}/${{ secrets.DOCKER_REPO }}:api-latest
          build-args: |
            ENV_FILE=${{ secrets.ENV_FILE }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            docker stop $(docker ps -a -q)
            docker login -u ${{secrets.DOCKER_USER}} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:api-latest
            docker run -dit -p 8080:8080 ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:api-latest
      - name: Cleanup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            docker system prune -f

  migrations:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Run Database Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            docker run ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:api-latest npm run migrate:run
