name: Deploy dev branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          source: "dist/*"
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          target: /var/www/app/html
          strip_components: 1
