steps:
  - name: gcr.io/cloud-builders/git
    args:
      - '-c'
      - |
        echo "$$ENV_FILE" >> .env
        chmod 400 .env
    entrypoint: bash
    secretEnv:
      - ENV_FILE
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/api:$SHORT_SHA', '-f', 'Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api:$SHORT_SHA' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'api',
      '--image',
      'gcr.io/$PROJECT_ID/api:$SHORT_SHA',
      '--region',
      'europe-west1',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--vpc-connector',
      'serverless-connector',
      '--min-instances',
      '1',
      '--cpu',
      '2',
      '--memory',
      '2Gi',
      '--concurrency',
      '20',
      '--port',
      '8080',
    ]
images:
  - 'gcr.io/$PROJECT_ID/api:$SHORT_SHA'
timeout: 3600s
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/api/versions/latest
      env: ENV_FILE
