name: Deploy main branch

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20' # Specify the version of Go.

      - name: Build binary
        run: |
          go build -o app ./src/cmd

      - name: Copy binary to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          source: "./app"
          target: "/root/app/"

      - name: Transfer restart script
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          source: "./restart.sh"
          target: "/root/app/"

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/hrm/api
            export SLACK_TOKEN=${{ secrets.SLACK_TOKEN }}
            export SLACK_CHANNEL_ID=${{ secrets.SLACK_CHANNEL_ID }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            export ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            chmod +x /root/hrm/api/restart.sh
            ./restart.sh > /dev/null 2>&1 &
